export type {
  Coding,
  CodeableConcept,
  Quantity,
  Reference,
  Period,
  Identifier,
  HumanName,
  Meta,
  ObservationComponent,
  FhirMeta,
  FhirCoding,
  FhirCodeableConcept,
  FhirIdentifier,
  FhirHumanName,
  FhirPatient,
} from "./fhir-r4.js";
